apiVersion: v1
kind: Service
metadata:
  name: atlhyper-controller
  namespace: {{ include "atlhyper.namespace" . }}
  labels:
    {{- include "atlhyper.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "atlhyper.controller.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - name: gateway
      port: 8080
      targetPort: 8080
    - name: agentsdk
      port: 8081
      targetPort: 8081
