{{- if ne (.Values.metrics.enabled | default true) false }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: atlhyper-metrics
  namespace: {{ include "atlhyper.namespace" . }}
  labels:
    {{- include "atlhyper.labels" . | nindent 4 }}
    {{- include "atlhyper.metrics.selectorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "atlhyper.metrics.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "atlhyper.metrics.selectorLabels" . | nindent 8 }}
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: atlhyper-metrics
          image: "bukahou/atlhyper-metrics:{{ include "atlhyper.imageTag" . }}"
          imagePullPolicy: Always
          securityContext:
            privileged: true
          envFrom:
            - configMapRef:
                name: atlhyper-config
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: proc-volume
              mountPath: /hostproc
              readOnly: true
            - name: sys-volume
              mountPath: /hostsys
              readOnly: true
            - name: root-volume
              mountPath: /host_root
              readOnly: true
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
      volumes:
        - name: proc-volume
          hostPath:
            path: /proc
            type: Directory
        - name: sys-volume
          hostPath:
            path: /sys
            type: Directory
        - name: root-volume
          hostPath:
            path: /
            type: Directory
{{- end }}
