apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "atlhyper.namespace" . }}
  labels:
    {{- include "atlhyper.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/resource-policy": keep
