apiVersion: v1
kind: Secret
metadata:
  name: atlhyper-secret
  namespace: {{ include "atlhyper.namespace" . }}
  labels:
    {{- include "atlhyper.labels" . | nindent 4 }}
type: Opaque
stringData:
  MASTER_ADMIN_USERNAME: {{ .Values.secret.admin.username | default "admin" | quote }}
  MASTER_ADMIN_PASSWORD: {{ .Values.secret.admin.password | default "changeme" | quote }}
  MASTER_ADMIN_DISPLAY_NAME: {{ .Values.secret.admin.displayName | default "Administrator" | quote }}
  MASTER_JWT_SECRET: {{ .Values.secret.jwt.secret | default "change-me-in-production" | quote }}
