apiVersion: v1
kind: Namespace
metadata:
  name: atlhyper
---
# ===============================
# AtlHyper Controller（内嵌 env）
# ===============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlhyper-controller
  namespace: atlhyper
  labels:
    app: atlhyper-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlhyper-controller
  template:
    metadata:
      labels:
        app: atlhyper-controller
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: "desk-zero"
      # tolerations:
      #   - key: "node-role.kubernetes.io/control-plane"
      #     operator: "Exists"
      #     effect: "NoSchedule"
      #   - key: "node-role.kubernetes.io/master"
      #     operator: "Exists"
      #     effect: "NoSchedule"
      containers:
        - name: controller
          image: bukahou/atlhyper-controller:v1.1.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
          env:
            # === 邮件配置（非敏感 + 密码）===
            - name: MAIL_USERNAME
              value: "xxxxxxxxxx@gmail.com"
            - name: MAIL_PASSWORD
              value: "sybjgnpqgrrayxol"
            - name: MAIL_FROM
              value: "xxxxxxxxxx@gmail.com"
            - name: MAIL_TO
              value: "xxxxxxxxxx@gmail.com"

            # === 控制项（布尔作为字符串）===
            - name: SLACK_WEBHOOK_URL
              value: "https://hooks.slack.com/services/T091E8J4QLD/xxxxxxxxxx/xxxxxxxxxx"
            - name: ENABLE_EMAIL_ALERT
              value: "false"
            - name: ENABLE_SLACK_ALERT
              value: "false"
            - name: ENABLE_WEBHOOK_SERVER
              value: "false"

            # === 管理员默认配置 ===
            - name: DEFAULT_ADMIN_USERNAME
              value: "xxxxxxxxxx"
            - name: DEFAULT_ADMIN_PASSWORD
              value: "xxxxxxxxxx"
            - name: DEFAULT_ADMIN_DISPLAY_NAME
              value: "Atlhyper"
            - name: DEFAULT_ADMIN_EMAIL
              value: "xxxxxxx@atlhyper.com"

          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: atlhyper-controller
  namespace: atlhyper
spec:
  selector:
    app: atlhyper-controller
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
